services:
  python:
    build:
      context: .
      dockerfile: ./infra/docker/development/python/Dockerfile
    volumes:
      - ./serverless:/serverless
    environment:
      - ENV=local
      - AWS_ACCESS_KEY_ID="dummy"
      - AWS_SECRET_ACCESS_KEY="dummy"

  sls-deploy:
    build:
      context: .
      dockerfile: ./infra/docker/development/sls-deploy/Dockerfile
    platform: linux/amd64
    volumes:
      - ./serverless:/serverless
      - ~/.aws:/root/.aws
      - serverless-node_modules:/serverless/node_modules
    tty: true
    ports:
      #(awccliのコールバックポート、基本はホスト側でログインするべきだけど)
      - 40237:40237


volumes:
  serverless-node_modules: